
const count = {}

export default [
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `McDonald's`,
    packetState: 'Empty',
    orientation: 'Horizontal',
  },
  {
    id: 1,
    condiment: 'Ketchup',
    brand: `Ketchup`,
    packetState: 'Empty',
    orientation: 'Horizontal',
  },
  {
    id: 2,
    condiment: 'Hot Sauce',
    brand: `Frank's RedHot`,
    packetState: 'Full',
    orientation: 'Vertical',
  },
  {
    id: 3,
    condiment: 'Ketchup',
    brand: `Sysco/Heinz`,
    packetState: 'Splattered',
    orientation: 'Vertical',
  },
  {
    id: 4,
    condiment: 'Ketchup',
    brand: `Red Gold`,
    packetState: 'Full',
    orientation: 'Horizontal',
  },
  {
    id: 5,
    condiment: 'Ketchup',
    brand: `Hunts`,
    packetState: 'Splattered',
    orientation: 'Vertical',
  },
  {
    id: 6,
    condiment: 'Ketchup',
    brand: `Heinz`,
    packetState: 'Empty',
    orientation: 'Vertical',
  },
  {
    id: 7,
    condiment: 'Hot Sauce',
    brand: `Louisiana`,
    packetState: 'Empty',
    orientation: 'Horizontal',
  },
  {
    id: 8,
    condiment: 'Ketchup',
    brand: `Heinz`,
    packetState: 'Splattered',
    orientation: 'Vertical',
  },
  {
    id: 9,
    condiment: 'Grape Jelly',
    brand: `Popeye's`,
    packetState: 'Empty',
    orientation: 'Horizontal',
  },


  {
    id: 10,
    condiment: 'Ketchup',
    brand: `Red Gold`,
    packetState: 'Empty',
    orientation: 'Horizontal',
  },
  {
    id: 11,
    condiment: 'Ketchup',
    brand: `Fancy Ketchup`,
    packetState: 'Empty',
    orientation: 'Horizontal',
  },
  {
    id: 12,
    condiment: 'Hot Sauce',
    brand: `Cholula`,
    packetState: 'Full',
    orientation: 'Vertical',
  },
  {
    id: 13,
    condiment: 'Mayonnaise',
    brand: `Chef's Quality`,
    packetState: 'Full',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `McDonald's`,
    packetState: 'Full',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `McDonald's`,
    packetState: 'Full',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Chef's Quality`,
    packetState: 'Splattered',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Grape Jelly',
    brand: `Popeye's`,
    packetState: 'Full',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Hot Sauce',
    brand: `YiPin`,
    packetState: 'Full',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Chef's Quality`,
    packetState: 'Empty',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Mayonnaise',
    brand: `Salad Fresh`,
    packetState: 'Empty',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Hunts`,
    packetState: 'Empty',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Heinz`,
    packetState: 'Empty',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Soy Sauce',
    brand: `Yamasa`,
    packetState: 'Full',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `French's`,
    packetState: 'Empty',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Heinz`,
    packetState: 'Splattered',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Heinz`,
    packetState: 'Splattered',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `McDonald's`,
    packetState: 'Full',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Sugar',
    brand: `Pure Sugar`,
    packetState: 'Full',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Mustard',
    brand: `Salad Fresh`,
    packetState: 'Empty',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Heinz`,
    packetState: 'Empty',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Ketchup`,
    packetState: 'Empty',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `White Castle`,
    packetState: 'Splattered',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Hunts`,
    packetState: 'Full',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Mustard',
    brand: `Flavor Fresh`,
    packetState: 'Full',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Chef's Quality`,
    packetState: 'Splattered',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Chef's Quality`,
    packetState: 'Empty',
    orientation: 'Horizontal',
  },
  {
    id: 0,
    condiment: 'BBQ Sauce',
    brand: `McDonald's`,
    packetState: 'Splattered',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `White Castle`,
    packetState: 'Empty',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Heinz`,
    packetState: 'Empty',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Heinz`,
    packetState: 'Splattered',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Duck Sauce',
    brand: `YiPin`,
    packetState: 'Full',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Hot Sauce',
    brand: `YiPin`,
    packetState: 'Full',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Grape Jelly',
    brand: `Popeye's`,
    packetState: 'Full',
    orientation: 'Horizontal',
  },


  {
    id: 0,
    condiment: 'Duck Sauce',
    brand: `YiPin`,
    packetState: 'Splattered',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Hot Sauce',
    brand: `Tabasco`,
    packetState: 'Full',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Hot Sauce',
    brand: `Popeye's`,
    packetState: 'Full',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Heinz`,
    packetState: 'Splattered',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Heinz`,
    packetState: 'Empty',
    orientation: 'Vertical',
  },
  {
    id: 0,
    condiment: 'Ketchup',
    brand: `Charleys`,
    packetState: 'Empty',
    orientation: 'Horizontal',
  },

  {
    id: 0,
    condiment: 'Soy Sauce',
    brand: `Yamasa`,
    packetState: 'Full',
    orientation: 'Horizontal',
  },

].map((d, id) => {

  if (!count[d.condiment]) {
    count[d.condiment] = 1
  }

  const name = d.condiment + ' #' + count[d.condiment]
  count[d.condiment]++
  return {
    id,
    name,
    license: 'CC BY-NC 4.0',
    external_url: `https://steviep.xyz/packets/${id}`,
    description: `As you wander along the sidewalk your mind also wanders -- but your eyes continue to scan the ground. Your ancestors foraged for nuts and berries, but you're looking for something different. Eventually your eyes pick something up in distance. You walk over to inspect it a little closer. Bending over, you think: "Oh wow, this is a good one!" A confused stranger looks up from their phone and rolls their eyes. They don't understand that this ketchup packet is worth hundreds of dollars on the internet.`,
    attributes: [
      { trait_type: 'Brand', value: d.brand },
      { trait_type: 'Condiment', value: d.condiment },
      { trait_type: 'Packet State', value: d.packetState },
      { trait_type: 'Orientation', value: d.orientation },
    ],
  }
})